Zuiso-28-marcos formulario
Zuiso-Tournaments/zuiso-tournaments pull request #21
Opened 2024-07-15 16:31 UTC by garmo17

Añadido el formulario

2024-07-18 12:11 UTC, garmo17 commented
vale me he equivocado y he hecho lo de la api tmb en esta rama xd

2024-07-21 06:54 UTC, MdeMora requested changes
Cambiar lo del link,

Entiendo que esto no es ZUISO-28: Marcos formulario si no ZUISO-31

2024-07-21 06:54 UTC, MdeMora commented on components/ui/Pricing/Pricing.tsx
> +import { Button } from '@/components/ui/button';
thx 👍

2024-07-21 06:54 UTC, MdeMora commented on app/api/MarcosAPI/music.json
> +        "artista": "Taylor Swift",
no sabia que eras swiftie 👎

2024-07-21 06:54 UTC, MdeMora commented on app/about/Marcos/SongList.tsx
> +                      <a href={`/about/Marcos/music/${song.id}`} className="text-blue-500 hover:text-blue-700 underline">View song</a>
para paginas internas usar <Link/> de next/navigation (creo que es next navigation, si no algo parecido)

2024-07-21 13:15 UTC, garmo17 commented on app/api/MarcosAPI/music.json
> +        "artista": "Taylor Swift",
no lo soy pero es por si lo ve una swiftie algun dia 😇

2024-07-21 13:29 UTC, garmo17 commented
no es que sea zuiso-31-Marcos-API, es que en este pull request esta lo del formulario y lo de la api, al clonar todo de nuevo se me olvido e hice todo en la rama del formulario que es la 28 pero estos cambios deberian estar hehcos en la 31 que es la tarea de jira de la api

2024-07-21 14:26 UTC, MdeMora approved these changes
LGTM

2024-07-21 15:23 UTC, merged