Zuiso 11 marcos funcionalidad del dado
Zuiso-Tournaments/zuiso-tournaments pull request #7
Opened 2024-07-11 11:31 UTC by garmo17

he añadido lo la tarea del dado

2024-07-11 21:51 UTC, MdeMora requested changes

2024-07-11 21:51 UTC, MdeMora commented on app/about/Marcos/dice.tsx
> +const DiceApp = () => {
Siempre en React para que sea mas claro ponemos el mismo nombre al fichero que al componente, en este caso le cambiariamos  el nombre de dice.tsx a DiceApp.tsx

2024-07-11 21:51 UTC, MdeMora commented on app/about/Marcos/dice.tsx
> +                ))}
Entiendo lo que haces y te ha quedado muy chula la funcionalidad pero el codigo te ha quedado un poco enrevesado, a ver si saco un ratito mañana y te paso un ejemplo de como estaria hecho más legible.

Pero vamos, esta super bien que hayas hecho esto, a tope :D

2024-07-13 12:37 UTC, garmo17 commented
He refactorizado el código, creo que ya esta mucho mejor y es todo mas sencillo.

2024-07-14 09:14 UTC, MdeMora approved these changes
LGTM. Ha quedado mucho mas legible y se entiende mucho mejor.  👏

2024-07-14 10:00 UTC, merged